timeSite/homeApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "main"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('demo/', views.demo, name='demo'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('calendar/', views.calendar, name='calendar'),
    path('contact/',views.contact, name='contact'),
    # path('index/', views.index, name='index'),
    # path('test/oneproject', views.oneProject, name='one'),
    # path('add/', views.add, name='add'),
    # path('copy/', views.copy, name='copy'),
    #path('demo/submit/<list_id>', views.submit, name='submit'),
]

timeSite/timeSite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as users_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeApp.urls')),
]

timeSite/homeApp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
# Create your models here.

class TutorialCategory(models.Model):
	tutorial_category = models.CharField(max_length=200)
	category_summary = models.CharField(max_length=200)
	category_slug = models.CharField(max_length=200)

	class Meta:
		verbose_name_plural = "Categories"

	def __str__(self):
		return self.tutorial_category


class TutorialSeries(models.Model):
	tutorial_series = models.CharField(max_length=200)
	tutorial_category = models.ForeignKey(TutorialCategory, default=1, verbose_name="Category", on_delete=models.SET_DEFAULT)
	series_summary = models.CharField(max_length=200)

	class Meta:
		verbose_name_plural = "Series"

	def __str__(self):
		return self.tutorial_series	


class Tutorial(models.Model):
	tutorial_title = models.CharField(max_length=200)
	tutorial_content = models.TextField()
	tutorial_published = models.DateTimeField("date published", default=datetime.now())

	tutorial_series = models.ForeignKey(TutorialSeries, default=1, verbose_name="Series", on_delete=models.SET_DEFAULT)
	tutorial_slug = models.CharField(max_length=200, default=1)

	def __str__(self):
		return self.tutorial_title

class List(models.Model):
	item = models.CharField(max_length=200, blank=True)
	curr_user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)

	def __str__(self):
		return self.item

class Project(models.Model):
	entry_date = models.DateTimeField(auto_now=True)
	entry_hour = models.DecimalField(default=0, max_digits=5, decimal_places=2)

	entry_user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
	entry_project = models.ForeignKey(List, on_delete=models.CASCADE, default=0)

	def __str__(self):
		return self.entry_date.strftime("%m:%d:%Y")

timeSite/homeApp/forms.py
from django import forms
from .models import List, Project
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class ProjectForm(forms.ModelForm):
	entry_hour = forms.DecimalField(required=True, max_digits=5, decimal_places=2)

	class Meta:
		model = Project
		fields = ["entry_hour"]

class ListForm(forms.ModelForm):
	item = forms.CharField(required=True)
	# curr_user = forms.ModelChoiceField(queryset=User.objects.all())

	class Meta:
		model = List
		fields = ["item"]

	# def save(self, commit=True):
	# 	List = super(ListForm, self).save(commit=False)
	# 	if commit:
	# 		List.save()
	# 	return List

	def clean_item(self):
		item = self.cleaned_data.get('item')
		if item == '':
			raise forms.ValidationError("Invalid name!")
		else:
			return item

timeSite/homeApp/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404, HttpResponse
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import NewUserForm, ListForm, ProjectForm
from .models import List, User, Project


# def index(request):
# 	return render(request, 'homeApp/index.html')

def homepage(request):
	return render(request, 'homeApp/home.html')

def calendar(request):
	return render(request, 'homeApp/calendar.html')

def contact(request):
	return render(request, 'homeApp/contact.html')

def dashboard(request):
	L = List.objects.filter(curr_user_id=request.user.id)
	if request.method == 'POST':
		if 'item' in request.POST:
			form = ListForm({'item': request.POST['item']})
			if form.is_valid():
				instance = form.save(commit=False)
				instance.curr_user = request.user
				instance.save()
				# a = list(L.cleaned_data['pk'])
				L = List.objects.filter(curr_user_id=request.user.id).last()
				# print(L.pk)
				data = {'message': "Valid project added method.", 'ID': L.pk}
			else:
				data = {'message': "Invalid project added method.", 'ID': L.pk}
			# return render(request, 'homeApp/demo.html', context={'data': data})
			return JsonResponse(data)
		else:
			ttls = request.POST['value']
			h = ttls[:2]
			m = ttls[3:5]
			s = ttls[-2:]
			t = int(h) + int(m)/60 + int(s)/3600
			form = ProjectForm({'entry_hour': t})
			if form.is_valid():
				instance = form.save(commit=False)
				instance.entry_user = request.user
				# print(request.POST.get('submit'))
				instance.entry_project = List.objects.get(pk=request.POST.get('submit'))
				instance.save()
				data = {
                	'message': "Successfully submitted form data."
            	}
				return JsonResponse(data)
	elif request.method == 'GET' and 'delete' in request.GET:
		# print(request.GET['delete'])
		item = List.objects.get(pk=request.GET['delete'])
		item.delete()
		# messages.success(request, ('Item deleted!'))
	return render(request, 'homeApp/dashboard.html', context={'all_items': L})

def demo(request):
	return render(request, 'homeApp/demo.html')

def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f"New Account Create: {username}")
			login(request, user)
			return redirect("main:homepage")
		else:
			for msg in form.error_messages:
				messages.error(request, f"{msg}: {form.error_messages[msg]}")
	form = NewUserForm
	return render(request, 
					"homeApp/register.html",
					context={"form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "Logged out successfully!")
	return redirect("main:homepage")

def login_request(request):
	if request.method == 'POST':
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, "Logged in successfully!")
				return redirect("main:homepage")
			else:
				messages.error(request, "Invalid username or password!")
		else:
			messages.error(request, "Invalid username or password!")

	form = AuthenticationForm()
	return render(request,
					"homeApp/login.html",
					context={"form":form})

timeSite/homeApp/templates/homeApp/base.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!--Bootstrap-->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		<script src="{% static 'homeApp/js/support.js' %}"></script>
		<script src="{% static 'homeApp/js/materialize.js' %}"></script>
		<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
		<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> 
		<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.min.js"></script>

		<title>Time Manager</title>
		<style>
			.footer {
			  	padding-top: 5rem;
			  	padding-bottom: 5rem;
			  	background-color: #2c3e50;
			  	color: #fff;
			}


		</style>
	</head>
	<body>
		{% include "homeApp/includes/navbar.html" %}

		{% block content %}
		{% endblock %}

	  	<!-- Footer -->
	  	<footer class="footer text-center">
		    <div class="container">
		      	<div class="row">
			        <!-- Footer Location -->
			        <div class="col-lg-4 mb-5 mb-lg-0">
			          	<h4 class="text-uppercase mb-4">Email</h4>
			          	<p class="lead mb-0">mablic@hotmail.com</p>
			        </div>

			        <!-- Footer Social Icons -->
			        <div class="col-lg-4 mb-5 mb-lg-0">
			          	<h4 class="text-uppercase mb-4">Contact Me</h4>
			          	<a class="btn btn-outline-light btn-social mx-1" href="{% url 'main:contact' %}">
			            	<i class="fab fa-fw fa-dribbble"></i>
			          	</a>
			        </div>

			        <!-- Footer About Text -->
			        <div class="col-lg-4">
			          	<h4 class="text-uppercase mb-4">About Me</h4>
			          	<p class="lead mb-0">Check out my
			            <a href="https://github.com/mablic">Github</a>.</p>
			        </div>

		      	</div>
		    </div>
	  	</footer>

			<!-- Optional JavaScript -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

timeSite/homeApp/templates/homeApp/demo.html
{% extends "homeApp/home.html" %}
{% block content %}
{% load static %}


<style>
    .left_bar {
        width: 160px;
        position: fixed;
        padding-top: 20px;
        padding-left: 20px;
    }
    .right_bar {
        padding-left: 320px;
        padding-right: 20px;
        padding-top: 20px;
    }
    table.tr.th {
        font-family: sans-serif;
    }
</style>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom" style="margin-right: 20px" id="date_selector">
    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <div>
            <input id="date_picker" type="text">
        </div>
    </div>
</div>

<div style="width: 100%">
    <div class="left_bar">
        <div id="send_data_form" action="{% url 'main:demo' %}">
            <form method="POST" style="width: 280px;">
                {% csrf_token %}
                <table style="word-break: break-word;">
                    <tr>
                        <th>
                            <input id= "input_field" class="form-control" type="text" placeholder="Add Item" aria-label="Search" name="item">
                        </th>
                        <th>
                            <button id="new_project_button" class="btn btn-outline-info" type="submit">
                                Add
                            </button>
                        </th>
                    </tr>
                </table>
            </form>
        </div>
        <br>
        <div id="project_temp_div" style="display: none;padding: 1px;">
            <div class="close">
                <small>
                    <sup>
                        <a id="temp_delete" onclick="delete_project(this)" href="#0">x</a>
                    </sup>
                </small>
            </div>
            <table style="word-break: break-word;">
                <tbody>
                    <tr>
                        <th>x</th>
                    </tr>
                    <tr>
                        <td><div id="project_temp_display">00:00:00</div></td>
                    </tr>
                </tbody>
            </table>
            <button class="btn btn-outline-info btn-sm" onclick="change_color(this)">Color</button>
            <button class="btn btn-outline-info btn-sm">Start</button>
            <button class="btn btn-outline-info btn-sm">Reset</button>
            <button class="btn btn-outline-info btn-sm" onclick="submit_project(this)">Submit</button>
            <input type="color" id="temp_id" parent="temp_parent" style="display: none;">
        </div>
        <div id="all_project" class="card border-1" style="width: 17rem; border: none;">
            <div id="project_list" class="card-body" style="padding: 0.2rem;">
                {% if all_items %}
                    {% for things in all_items %}
                        <div id="project_item_div_{{ forloop.counter0 }}" style="padding: 1px;">
                            <!-- <div id="draggable"> -->
                            <div class="close">
                                <small>
                                    <sup>
                                        <!--item_delete_{{ forloop.counter0 }}-->
                                        <a parent="project_item_div_{{ forloop.counter0 }}" onclick="delete_project(this)" value="{{things.id}}" href="#0">x</a>
                                    </sup>
                                </small>
                            </div>
                            <table style="word-break: break-word;">
                                <tbody>
                                    <tr>
                                        <th>{{ things.item }}</th>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id = "item_display_{{ forloop.counter0 }}">
                                                00:00:00
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <button class="btn btn-outline-info btn-sm" id="item_change_color_{{forloop.counter0}}" parent="{{forloop.counter0}}" onclick="change_color(this)">Color</button>
                            <button 
                            class="btn btn-outline-info btn-sm" id="item_start_stop_{{ forloop.counter0 }}"
                                onclick="item_start_stop_('{{forloop.counter0}}')">Start</button>
                            <button 
                            class="btn btn-outline-info btn-sm" id="item_reset_{{ forloop.counter0 }}"
                                onclick="item_reset_('{{forloop.counter0}}')">Reset</button>
                            <button 
                            class="btn btn-outline-info btn-sm" id="item_submit_{{ forloop.counter0 }}"
                                value = "{{things.id}}" onclick="submit_project(this)"
                                parent = "{{ forloop.counter0 }}">Submit</button>
                            <input type="color" id="color_input_{{ forloop.counter0 }}" parent="{{ forloop.counter0 }}" style="display: none;">
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="right_bar">
        {% include "homeApp/calendar.html" %}
    </div>
</div>

<script>
    $(document).ready(function(){
        var $myForm = $("#send_data_form");
        var projectButton = $('#new_project_button');
        var projectList = $('#project_list');
        var projectInput = document.getElementById('input_field');
        var tempProject = document.getElementById("project_temp_div");
        $('#date_picker').datepicker({
            format: "mm/dd/yyyy",
            showOn: "button",
            buttonImage: "{% static 'homeApp/images/calendar.gif' %}",
            // buttonImage: "images/calendar.gif",
            buttonImageOnly: true,
            buttonText: "Select date",
            showWeek: true,
            firstDay: 1,
            todayHighlight: true,
        });
        $myForm.submit(function(event) {
            var PROJECT_COUNT = $('#project_list>div').length;
            event.preventDefault();
            var cln = tempProject.cloneNode(true);
            projectList.append(cln);

            var currProject = projectList.find('#project_temp_div');
            // tempProject = currProject[currProject.length-3]; // last 3 div is the project div
            currProject[0].style = "padding: 5px;"; // reset the style of current project
            currProject[0].id = "project_item_div_" + PROJECT_COUNT;

            var newTr = currProject.find("tr");
            newTr[0].innerHTML = "<th>" + projectInput.value + "</th>"// add project

            var tempDisplay = currProject.find('div'); // last 2 div is the time div
            tempDisplay[1].id = "item_display_" + PROJECT_COUNT;

            var deleteButton = currProject.find('#temp_delete');
            deleteButton[0].id =  "item_delete_" + PROJECT_COUNT;
            deleteButton = $('#item_delete_' + PROJECT_COUNT);
            deleteButton.attr('parent', 'project_item_div_' + PROJECT_COUNT);

            var currButton = currProject.find("button");
            var tempButton = currButton[0];
            tempButton.id = "item_change_color_" + PROJECT_COUNT;
            tempButton.setAttribute("parent", PROJECT_COUNT);

            tempButton = currButton[1];
            tempButton.id = "item_start_stop_" + PROJECT_COUNT;
            tempButton = currButton[2];
            tempButton.id = "item_reset_" + PROJECT_COUNT;
            tempButton = currButton[3];
            tempButton.id = "item_submit_" + PROJECT_COUNT;

            tempButton = $("#item_start_stop_" + PROJECT_COUNT);    // onclick function setup
            tempButton.attr("onclick", "item_start_stop_('" + PROJECT_COUNT + "')");            
            tempButton = $("#item_reset_" + PROJECT_COUNT);
            tempButton.attr("onclick", "item_reset_('" + PROJECT_COUNT + "')");

            tempButton = $("#item_submit_" + PROJECT_COUNT);
            tempButton.attr("parent",  PROJECT_COUNT);

            var colorInput = currProject.find('input');
            colorInput.attr("id", "color_input_" + PROJECT_COUNT);
            colorInput.attr("parent", PROJECT_COUNT);

            var $thisURL = $myForm.attr('action');
            $.ajax({
                type: 'post',
                headers: { "X-CSRFToken": '{{csrf_token}}' },
                url: $thisURL,
                data: { 'item' : projectInput.value },
            }).done(function(result) {
                var deleteButton = $('#item_delete_' + (PROJECT_COUNT-1));
                deleteButton.attr('value', result["ID"])
                var submitButton = $('#item_submit_' + (PROJECT_COUNT-1));
                submitButton.attr('value', result["ID"])
            });
            PROJECT_COUNT++;
        });
    });
    $('#project_list').sortable({
        revert:true
    });
    function change_color(projectID){
        var retID = $(projectID).attr('parent');
        $('#color_input_' + retID).click();
        jQuery('#color_input_' + retID).on('change', function(){
           $('#project_item_div_' + retID).css("background-color", jQuery(this).val());
        });
    };
    function delete_project(ret){
        var $thisURL = {% url 'main:demo' %};
        $.ajax({
            type: 'get',
            data: {'delete': $(ret).attr('value')},
            url: $thisURL,
        }).done(function(result) {
            // console.log($(ret).attr('parent'));
            var parentID = $(ret).attr('parent');
            document.getElementById(parentID).remove();
        });
    };
    function submit_project(ret){
        var $thisURL = {% url 'main:demo' %};
        var parentID = $(ret).attr('parent');
        var totalTime = document.getElementById("item_display_" + parentID).innerText;
        // console.log(totalTime);
        $.ajax({
            type: 'post',
            headers: { "X-CSRFToken": '{{csrf_token}}' },
            data: {'submit': $(ret).attr('value'), 'value': totalTime},
            url: $thisURL,
        }).done(function(result) {
            item_reset_(parentID);
        });
    };
</script>

{% endblock content %}

timeSite/homeApp/templates/homeApp/home.html
{% extends "homeApp/base.html" %}
{% load static %}
{% block content %}

<style type="text/css">
    .container {
      width: 100%;
      padding-right: 15px;
      padding-left: 15px;
      margin-right: auto;
      margin-left: auto;
    }

    @media (min-width: 576px) {
      .container {
        max-width: 540px;
      }
    }

    @media (min-width: 768px) {
      .container {
        max-width: 720px;
      }
    }

    @media (min-width: 992px) {
      .container {
        max-width: 960px;
      }
    }

    @media (min-width: 1200px) {
        .container {
            max-width: 1140px;
        }
    }

    .container-fluid {
        width: 100%;
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
    }
    
</style>

<!-- Masthead -->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column" style="width: 30%">
        <!-- Masthead Avatar Image -->
        <br><br><br>
        <img class="masthead-avatar mb-5" src="{%static 'homeApp/images/header.JPG' %}" alt="">
        <!-- '{%static 'homeApp/img/avataaars.svg' %}' -->
        <!-- Masthead Heading -->
        <h1 class="masthead-heading text-uppercase mb-0">Time Manager</h1>

        <!-- Icon Divider -->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
          <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Masthead Subheading -->
        <p class="masthead-subheading font-weight-light mb-0">Easy way to check your time</p>
        <div class="row" style="padding: 20px;">
            <button onclick="sign_up_function()" type="button" class="btn btn-outline-light btn-lg">Sign up</button>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <button onclick="github_function()" type="button" class="btn btn-outline-light btn-lg">Git Hub</button>
        </div>
    </div>
</header>
<br><br>
<!-- Portfolio Grid Items -->

<section class="page-section portfolio" id="portfolio">
    <div class="container">
        <!-- Portfolio Section Heading -->
        <h2 class="text-center">Portfolio</h2>
        <div class="row">
            <div class="col-md-6 col-lg-4">
                <div id='portfolio1'>
                    <img class="img-fluid" src="{%static 'homeApp/img/portfolio/cabin.png' %}" alt="">
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                <div id='portfolio2'>
                    <img class="img-fluid" src="{%static 'homeApp/img/portfolio/cake.png' %}" alt="">
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                <div id='portfolio3'>
                    <img class="img-fluid" src="{%static 'homeApp/img/portfolio/circus.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<br>

<div id="portfolioNote1" style="display: none;">
    <header style="text-align: center;">Easy</header>
    <p style="word-wrap: break-word;padding: 5px;">Time manager provides easy solution for personal or cooperation uses. It allows user to have full control of their daily exerices, allow they to customize their day as needed.</p>
</div>
<div id="portfolioNote2" style="display: none;">
    <header style="text-align: center;">Automate</header>
    <p style="word-wrap: break-word;padding: 5px;">Time manager automate your daily exercise by having your every day data storaged on our secure database, you can always look back what you did for the day!</p>
</div>
<div id="portfolioNote3" style="display: none;">
    <header style="text-align: center;">Free</header>
    <p style="word-wrap: break-word;padding: 5px;">Time manager is a free application that you can use on daily basis. Relax, we wouldn't charge you until i broke!</p>
</div>

<script type="text/javascript">
    function sign_up_function() {
        // window.open("{% url 'main:register' %}"); 
        alert('This is currently under development, please contact me for more details.');
    }
    function github_function() {
        window.open("https://github.com/mablic");
    }
    $(document).ready(function(){
        var state1 = true;
        $('#portfolio1').click(function (e) {
            if (state1){
                $('#portfolio1').animate({
                  backgroundColor: "#aa0000",
                  color: "#fff",
                  height: 400
                }, 1000 );
                var tmp = $('#portfolioNote1').clone();
                tmp.css('display','inline');
                $('#portfolio1').append(tmp);
            }else{
                $( "#portfolio1" ).animate({
                  backgroundColor: "#fff",
                  color: "#000",
                  height: 350
                }, 1000 );
                var tmp = $( "#portfolio1" ).find('#portfolioNote1');
                tmp.remove();
            }
            state1 = !state1;
        })
        var state2 = true;
        $('#portfolio2').click(function (e) {
            if (state2){
                $('#portfolio2').animate({
                  backgroundColor: "#aa0000",
                  color: "#fff",
                  height: 400
                }, 1000 );
                var tmp = $('#portfolioNote2').clone();
                tmp.css('display','inline');
                $('#portfolio2').append(tmp);
            }else{
                $( "#portfolio2" ).animate({
                  backgroundColor: "#fff",
                  color: "#000",
                  height: 350
                }, 1000 );
                var tmp = $( "#portfolio2" ).find('#portfolioNote2');
                tmp.remove();
            }
            state2 = !state2;
        })
        var state3 = true;
        $('#portfolio3').click(function (e) {
            if (state3){
                $('#portfolio3').animate({
                  backgroundColor: "#aa0000",
                  color: "#fff",
                  height: 400
                }, 1000 );
                var tmp = $('#portfolioNote3').clone();
                tmp.css('display','inline');
                $('#portfolio3').append(tmp);
            }else{
                $( "#portfolio3" ).animate({
                  backgroundColor: "#fff",
                  color: "#000",
                  height: 350
                }, 1000 );
                var tmp = $( "#portfolio3" ).find('#portfolioNote3');
                tmp.remove();
            }
            state3 = !state3;
        })
    })
</script>>
{% endblock content %}

timeSite/homeApp/templates/homeApp/includes/navbar.html
{% block content %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand js-scroll-trigger" href="#page-top">TIME MANAGER</a>
	<div class="collapse navbar-collapse">
		<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
		</ul>
		<div class="navbar-nav my-2 my-lg-0" style="padding-right: 100px;">
			<a class="nav-link" href="{% url 'main:homepage' %}">Home <span class="sr-only">(current)</span></a>
			{% if user.is_authenticated %}
				<a class="nav-link" href="{% url 'main:dashboard' %}">Dashboard</a>
			{% else %}
				<a class="nav-link" href="{% url 'main:demo' %}">Demo</a>
			{% endif %}
			<a class="nav-link" href="{% url 'main:contact' %}">Contact<span class="sr-only">(current)</span></a>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Profile
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
					{% if user.is_authenticated %}
						<a class="dropdown-item" href="#">My Profile</a>
						<a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a>
					{% else %}
						<a class="dropdown-item" href="{% url 'main:login' %}">Sign in</a>
						<a class="dropdown-item" onclick="sign_up_function()">Register</a> <!--href="{% url 'main:register' %}" -->
					{% endif %}
				</div>
			</li>
			<li>&nbsp&nbsp&nbsp&nbsp&nbsp</li>
		</div>
	</div>
</nav>
<script type="text/javascript">
    function sign_up_function() {
        // window.open("{% url 'main:register' %}"); 
        alert('This is currently under development, please contact me for more details.');
    }
</script>

{% endblock content %}